### ISSUE TITLE
Unable to mount C with long directory while tinkering in IDE

### ISSUE THREAD

**Issue by Tennessene** [Tennessene/jDOSBox#7]
I have this error that only happens when I run jDOSBox in my Spigot plugin project in my IDE. It doesn't happen when running the jar. It's when I try to mount the C drive with a long directory (eg. C:\Users\Anston Sorensen\IdeaProjects\Plugin Development\VMComputers). The Java version doesn't matter. I don't understand why running jDOSBox inside the project vs the jar causes this.

Here is the stacktrace
```
java.lang.StringIndexOutOfBoundsException: begin 0, end 6, length 4
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4604)
	at java.base/java.lang.String.substring(String.java:2707)
	at jdos.dos.DOS_Drive_Cache.CompareShortname(DOS_Drive_Cache.java:591)
	at jdos.dos.DOS_Drive_Cache.CreateShortNameID(DOS_Drive_Cache.java:548)
	at jdos.dos.DOS_Drive_Cache.CreateShortName(DOS_Drive_Cache.java:488)
	at jdos.dos.DOS_Drive_Cache.CreateEntry(DOS_Drive_Cache.java:726)
	at jdos.dos.DOS_Drive_Cache.ReadDir(DOS_Drive_Cache.java:123)
	at jdos.dos.DOS_Drive_Cache.FindDirInfo(DOS_Drive_Cache.java:640)
	at jdos.dos.DOS_Drive_Cache.OpenDir(DOS_Drive_Cache.java:95)
	at jdos.dos.DOS_Drive_Cache.SetBaseDir(DOS_Drive_Cache.java:82)
	at jdos.dos.drives.Drive_local.<init>(Drive_local.java:152)
	at jdos.dos.Dos_programs$MOUNT.Run(Dos_programs.java:295)
	at jdos.misc.Program$1.call(Program.java:76)
	at jdos.Dosbox$1.call(Dosbox.java:75)
	at jdos.Dosbox.DOSBOX_RunMachine(Dosbox.java:205)
	at jdos.cpu.Callback.CALLBACK_RunRealInt(Callback.java:158)
	at jdos.shell.Dos_shell.Execute(Dos_shell.java:755)
	at jdos.shell.Dos_shell.DoCommand(Dos_shell.java:633)
	at jdos.shell.Dos_shell.ParseLine(Dos_shell.java:173)
	at jdos.shell.Dos_shell.Run(Dos_shell.java:98)
	at jdos.shell.Shell$5.call(Shell.java:398)
	at jdos.misc.setup.Config.StartUp(Config.java:97)
	at jdos.gui.MainBase.main(MainBase.java:536)
	at jdos.gui.MainFrame$4.run(MainFrame.java:247)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
I have no idea where to begin on this and again it's bizarre that this error happens only when I run jDOSBox in my project (via jdos.gui.MainFrame). It doesn't happen with `mount c c:\`

If simply trying to mount c where the project is at causes this then I will have to move the project to c:\

**Comment by Tennessene** [comment]
Okay, this is weird. So I have `mount c c:\` in my autoexec section, but the disk image file I'm boot into Windows 95 in is in `C:\VMComputers`, so that must mean you can mount C anywhere and still be able to use the disk image because it must grab the disk image from whatever directory it's working in?

**Comment by Tennessene** [comment]
Uh oh that's not the way it is in DOSBox. Time for some more parity!

**Comment by pietrygamat** [comment]
It seems to happen when mounting current working directory. I would expect this to happen in original jars too.

**Comment by Tennessene** [comment]
Okay, that makes more sense, but I guess since I figured out you don't need to mount if the disk image is in current directory, we don't have to fix this for my plugin, do we?
